[start]
command:/usr/local/opnsense/scripts/OPNsense/Gate/service.sh start
parameters:
type:script
message:Starting Gate Minecraft Proxy
description:Start Gate

[stop]
command:/usr/local/opnsense/scripts/OPNsense/Gate/service.sh stop
parameters:
type:script
message:Stopping Gate Minecraft Proxy
description:Stop Gate

[restart]
command:/usr/local/opnsense/scripts/OPNsense/Gate/service.sh restart
parameters:
type:script
message:Restarting Gate Minecraft Proxy
description:Restart Gate

[reload]
command:/usr/local/opnsense/scripts/OPNsense/Gate/service.sh reload
parameters:
type:script
message:Reloading Gate Minecraft Proxy
description:Reload Gate

[status]
command:/usr/local/opnsense/scripts/OPNsense/Gate/service.sh status
parameters:
type:script_output
message:Get Gate status
description:Gate status
